// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Artifact struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	MinRarity int          `json:"min_rarity" bson:"min_rarity"`
	MaxRarity int          `json:"max_rarity" bson:"max_rarity"`
	Flower    *ArtifactSet `json:"flower"`
	Plume     *ArtifactSet `json:"plume"`
	Sands     *ArtifactSet `json:"sands"`
	Goblet    *ArtifactSet `json:"goblet"`
	Circlet   *ArtifactSet `json:"circlet"`
	OnePc     *string      `json:"one_pc" bson:"one_pc"`
	TwoPc     *string      `json:"two_pc" bson:"two_pc"`
	FourPc    *string      `json:"four_pc" bson:"four_pc"`
}

type ArtifactSet struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type Ascension struct {
	Ascension *int               `json:"ascension"`
	Level     []*int             `json:"level"`
	Cost      *int               `json:"cost"`
	MatOne    *AscensionMaterial `json:"mat_one" bson:"mat1"`
	MatTwo    *AscensionMaterial `json:"mat_two" bson:"mat2"`
	MatThree  *AscensionMaterial `json:"mat_three" bson:"mat3"`
	MatFour   *AscensionMaterial `json:"mat_four" bson:"mat4"`
}

type AscensionMaterial struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Amount *int   `json:"amount"`
	Rarity *int   `json:"rarity"`
}

type Bait struct {
	ID          *string     `json:"id"`
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Rarity      *int        `json:"rarity"`
	Craft       *Craft      `json:"craft"`
	Fish        []*FishBait `json:"fish"`
}

type CalculateCharacterParams struct {
	CurrentLevel      *ExpLevel    `json:"currentLevel"`
	IntendedLevel     *ExpLevel    `json:"intendedLevel"`
	CurrentTalentLvl  *TalentLevel `json:"currentTalentLvl"`
	IntendedTalentLvl *TalentLevel `json:"intendedTalentLvl"`
}

type CalculateWeaponParams struct {
	CurrentLevel  *ExpLevel `json:"currentLevel"`
	IntendedLevel *ExpLevel `json:"intendedLevel"`
}

type CalculationCharacterResult struct {
	ExpWasted *int                     `json:"expWasted"`
	Items     []*CalculationItemResult `json:"items"`
}

type CalculationItemResult struct {
	ID     string `json:"id"`
	Img    string `json:"img"`
	Name   string `json:"name"`
	Amount int    `json:"amount"`
}

type Character struct {
	ID              string            `json:"id"`
	Name            string            `json:"name"`
	Title           string            `json:"title"`
	Description     string            `json:"description"`
	WeaponType      string            `json:"weapon_type" bson:"weapon_type"`
	Element         string            `json:"element"`
	Gender          string            `json:"gender"`
	Substat         string            `json:"substat"`
	Affiliation     string            `json:"affiliation"`
	Region          string            `json:"region"`
	Rarity          *int              `json:"rarity"`
	Birthday        []*int            `json:"birthday"`
	Constellation   string            `json:"constellation"`
	Domain          string            `json:"domain"`
	Cv              *CharacterVoice   `json:"cv"`
	Skills          []*Skill          `json:"skills"`
	Passives        []*Passive        `json:"passives"`
	Constellations  []*Constellation  `json:"constellations"`
	Ascension       []*Ascension      `json:"ascension"`
	TalentMaterials []*TalentMaterial `json:"talent_materials" bson:"talent_materials"`
}

type CharacterFood struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type CharacterInfo struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Title         string          `json:"title"`
	Description   string          `json:"description"`
	WeaponType    string          `json:"weapon_type" bson:"weapon_type"`
	Element       string          `json:"element"`
	Gender        string          `json:"gender"`
	Substat       string          `json:"substat"`
	Affiliation   string          `json:"affiliation"`
	Region        string          `json:"region"`
	Rarity        *int            `json:"rarity"`
	Birthday      []*int          `json:"birthday"`
	Constellation string          `json:"constellation"`
	Domain        string          `json:"domain"`
	Cv            *CharacterVoice `json:"cv"`
}

type CharacterVoice struct {
	English  string `json:"english"`
	Chinese  string `json:"chinese"`
	Japanese string `json:"japanese"`
	Korean   string `json:"korean"`
}

type CommonMaterial struct {
	ID          *string              `json:"id"`
	Name        *string              `json:"name"`
	Description *string              `json:"description"`
	Source      []*string            `json:"source"`
	Rarity      *int                 `json:"rarity"`
	Craft       *CommonMaterialCraft `json:"craft"`
}

type CommonMaterialCraft struct {
	Cost  *int                  `json:"cost"`
	Items []*CommonMaterialItem `json:"items"`
}

type CommonMaterialItem struct {
	ID     *string `json:"id"`
	Name   *string `json:"name"`
	Amount *int    `json:"amount"`
}

type Constellation struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Level       *int   `json:"level"`
}

type Craft struct {
	Items  []*CraftItem `json:"items"`
	Result *int         `json:"result"`
}

type CraftItem struct {
	ID     *string `json:"id"`
	Name   *string `json:"name"`
	Amount *int    `json:"amount"`
}

type CraftJewel struct {
	Cost  *int    `json:"cost"`
	Items []*Item `json:"items"`
}

type CraftPotion struct {
	Cost  *int    `json:"cost"`
	Items []*Item `json:"items"`
}

type CraftTalentLvlUp struct {
	Cost  *int    `json:"cost"`
	Items []*Item `json:"items"`
}

type CraftWeaponPrimary struct {
	Cost  *int    `json:"cost"`
	Items []*Item `json:"items"`
}

type CraftWeaponSecondary struct {
	Cost  *int    `json:"cost"`
	Items []*Item `json:"items"`
}

type ElementalStoneMaterial struct {
	ID          *string   `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Source      []*string `json:"source"`
	Rarity      *int      `json:"rarity"`
}

type ExpLevel struct {
	Lvl     int  `json:"lvl"`
	Asc     bool `json:"asc"`
	AsclLvl int  `json:"asclLvl"`
}

type ExpMaterial struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Rarity      int    `json:"rarity"`
	Exp         int    `json:"exp"`
}

type Fish struct {
	ID          string      `json:"id"`
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Rarity      *int        `json:"rarity"`
	Source      []*string   `json:"source"`
	Bait        *SimpleBait `json:"bait"`
}

type FishBait struct {
	ID     *string `json:"id"`
	Name   *string `json:"name"`
	Amount *int    `json:"amount"`
}

type FishingRod struct {
	ID          *string   `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Rarity      *int      `json:"rarity"`
	Source      []*string `json:"source"`
}

type Food struct {
	ID          *string       `json:"id"`
	Name        *string       `json:"name"`
	Description *string       `json:"description"`
	Ingredients []*Ingredient `json:"ingredients"`
	DishType    *string       `json:"dish_type" bson:"dish_type"`
	Results     *FoodResult   `json:"results"`
	Rarity      *int          `json:"rarity"`
}

type FoodResult struct {
	Normal     *FoodType    `json:"normal"`
	Delicious  *FoodType    `json:"delicious"`
	Suspicious *FoodType    `json:"suspicious"`
	Special    *FoodSpecial `json:"special"`
}

type FoodSpecial struct {
	Name        *string        `json:"name"`
	Description *string        `json:"description"`
	Effect      *string        `json:"effect"`
	Character   *CharacterFood `json:"character"`
}

type FoodType struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Effect      *string `json:"effect"`
}

type Ingredient struct {
	ID     *string `json:"id"`
	Name   *string `json:"name"`
	Amount *int    `json:"amount"`
}

type Ingredients struct {
	ID          *string   `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Processing  []*Item   `json:"processing"`
	Recipes     []*Recipe `json:"recipes"`
}

type Item struct {
	ID     *string `json:"id"`
	Name   *string `json:"name"`
	Amount *int    `json:"amount"`
}

type JewelMaterial struct {
	ID          *string     `json:"id"`
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Source      []*string   `json:"source"`
	Rarity      *int        `json:"rarity"`
	Craft       *CraftJewel `json:"craft"`
	Convert     [][]*Item   `json:"convert"`
}

type LocalMaterial struct {
	ID          *string   `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Source      []*string `json:"source"`
	Location    *string   `json:"location"`
}

type Passive struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Level       *int   `json:"level"`
}

type Potion struct {
	ID          *string      `json:"id"`
	Name        *string      `json:"name"`
	Description *string      `json:"description"`
	Effect      *string      `json:"effect"`
	Rarity      *int         `json:"rarity"`
	Craft       *CraftPotion `json:"craft"`
}

type Recipe struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type SimpleBait struct {
	ID     *string `json:"id"`
	Name   *string `json:"name"`
	Rarity *int    `json:"rarity"`
}

type Skill struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Description string            `json:"description"`
	Info        string            `json:"info"`
	Attributes  []*SkillAttribute `json:"attributes"`
}

type SkillAttribute struct {
	Label  string   `json:"label"`
	Values []string `json:"values"`
}

type StatLevel struct {
	Ascension *int     `json:"ascension"`
	Level     *int     `json:"level"`
	Primary   *int     `json:"primary"`
	Secondary *float64 `json:"secondary"`
}

type TalentLevel struct {
	Aa    int `json:"aa"`
	Skill int `json:"skill"`
	Burst int `json:"burst"`
}

type TalentLvlUpMaterial struct {
	ID          *string           `json:"id"`
	Name        *string           `json:"name"`
	Description *string           `json:"description"`
	Source      []*string         `json:"source"`
	Location    *string           `json:"location"`
	Rarity      *int              `json:"rarity"`
	Craft       *CraftTalentLvlUp `json:"craft"`
	Domain      *string           `json:"domain"`
	Days        []*string         `json:"days"`
}

type TalentMaterial struct {
	Level *int                 `json:"level"`
	Cost  *int                 `json:"cost"`
	Items []*AscensionMaterial `json:"items"`
}

type Weapon struct {
	ID          *string             `json:"id"`
	Name        *string             `json:"name"`
	Description *string             `json:"description"`
	Rarity      *int                `json:"rarity"`
	Type        *string             `json:"type"`
	Domain      *string             `json:"domain"`
	Passive     *string             `json:"passive"`
	Bonus       *string             `json:"bonus"`
	Stats       *WeaponStat         `json:"stats"`
	Ascensions  []*WeaponAscension  `json:"ascensions"`
	Refinements []*WeaponRefinement `json:"refinements"`
}

type WeaponAscension struct {
	Ascension *int                 `json:"ascension"`
	Level     *int                 `json:"level"`
	Cost      *int                 `json:"cost"`
	Materials []*AscensionMaterial `json:"materials"`
}

type WeaponInfo struct {
	ID          *string             `json:"id"`
	Name        *string             `json:"name"`
	Description *string             `json:"description"`
	Rarity      *int                `json:"rarity"`
	Type        *string             `json:"type"`
	Domain      *string             `json:"domain"`
	Passive     *string             `json:"passive"`
	Bonus       *string             `json:"bonus"`
	Stats       *WeaponStat         `json:"stats"`
	Refinements []*WeaponRefinement `json:"refinements"`
}

type WeaponPrimaryMaterial struct {
	ID          *string             `json:"id"`
	Name        *string             `json:"name"`
	Description *string             `json:"description"`
	Source      []*string           `json:"source"`
	Location    *string             `json:"location"`
	Rarity      *int                `json:"rarity"`
	Craft       *CraftWeaponPrimary `json:"craft"`
	Domain      *string             `json:"domain"`
	Days        []*string           `json:"days"`
}

type WeaponRefinement struct {
	Refinement *int    `json:"refinement"`
	Desc       *string `json:"desc"`
}

type WeaponSecondaryMaterial struct {
	ID          *string               `json:"id"`
	Name        *string               `json:"name"`
	Description *string               `json:"description"`
	Source      []*string             `json:"source"`
	Rarity      *int                  `json:"rarity"`
	Craft       *CraftWeaponSecondary `json:"craft"`
}

type WeaponStat struct {
	Primary   *string      `json:"primary"`
	Secondary *string      `json:"secondary"`
	Levels    []*StatLevel `json:"levels"`
}
