version: "3.9"

services:
  redis:
    image: redis:6.2.5-alpine
    volumes:
      - redis_data:/data
  db:
    image: mongo:5.0.3
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
  api:
    image: "${API_IMAGE}"
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
      - redis
  dataupdater:
    image: "${DATAUPDATER_IMAGE}"
    environment:
      ENVIRONMENT: production
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - /certs:/certs
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    depends_on:
      - api
      - dataupdater

volumes:
  db_data:
  redis_data: