version: "3.9"

services:
  redis:
    image: redis:6.2.5-alpine
    volumes:
      - redis_data:/data
  db:
    image: mongo:5.0.3
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
  api:
    image: "${API_IMAGE}"
    environment:
      ENVIRONMENT: production
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
      - redis
  dataupdater:
    image: "${DATAUPDATER_IMAGE}"
    environment:
      PORT: 3000
      ENVIRONMENT: production
      TOKEN: ${TOKEN}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${EMAIL}
      RENEWAL_INTERVAL: 8d
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - api
      - dataupdater

volumes:
  db_data: null
  redis_data: null
  nginx_secrets: null
