version: "3.9"
services:
  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    depends_on:
      - db
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - redis
  dataupdater:
    build:
      dockerfile: Dockerfile
      context: ./dataupdater
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
  redis_data: